import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {questions} from '../lib/assessment.ts';
import {headers,validateSubmission,prepareRow,signedEnvelope,writeSubmission} from '../lib/submission.ts';
import {handleSubmission} from '../lib/submission-handler.ts';
const secret='test-only-secret-not-a-real-credential-12345';
const fixture=()=>({submissionId:'b738ac10-a1e2-4001-bbbc-28ccb4143356',candidate:{name:'Тестовый Студент',group:'TEST-01',email:'test@example.com'},consent:true,answers:Object.fromEntries(questions.map(q=>[q.id,2])),website:''});
const req=(data:unknown,origin='https://digital-hub.example')=>new Request('https://digital-hub.example/api/submissions',{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify(data)});
test('server validates all answers and consent instead of accepting browser scores',()=>{const s=validateSubmission({...fixture(),scores:{motivation:100}});assert.equal(prepareRow(s).row[9],50);for(const change of [{consent:false},{answers:{}},{submissionId:'bad'},{website:'spam'}])assert.throws(()=>validateSubmission({...fixture(),...change}));assert.throws(()=>validateSubmission({...fixture(),candidate:{...fixture().candidate,email:'bad'}}));});
test('sheet row has 55 aligned columns and content hash remains stable for retries',()=>{const s=validateSubmission(fixture());const a=prepareRow(s,new Date(0)),b=prepareRow(s,new Date(1000));assert.equal(headers.length,55);assert.equal(a.row.length,55);assert.equal(a.hash,b.hash);assert.notEqual(a.row[2],b.row[2]);assert.notEqual(a.hash,prepareRow({...s,candidate:{...s.candidate,name:'Другой студент'}}).hash);});
test('writer only confirms matching acknowledgement, keeps secret out of payload',async()=>{const s=validateSubmission(fixture());let body='';const fetcher=(async(_url,init)=>{body=String(init?.body);return Response.json({ok:true,submissionId:s.submissionId});}) as typeof fetch;assert.deepEqual(await writeSubmission(s,{url:'https://script.google.com/macros/s/test/exec',secret},fetcher),{saved:true,submissionId:s.submissionId});assert.ok(!body.includes(secret));await assert.rejects(writeSubmission(s,{url:'https://evil.example/exec',secret},fetcher));await assert.rejects(writeSubmission(s,{url:'https://script.google.com/macros/s/test/exec',secret},async()=>Response.json({ok:false})));});
test('HTTP endpoint rejects cross-origin, malformed, oversized and incomplete requests before writing',async()=>{let calls=0;const writer=async()=>{calls++;return {saved:true,submissionId:fixture().submissionId};};assert.equal((await handleSubmission(req(fixture(),'https://evil.example'),{},writer)).status,403);assert.equal((await handleSubmission(req({}),{},writer)).status,400);assert.equal((await handleSubmission(req({padding:'x'.repeat(17000)}),{},writer)).status,413);assert.equal(calls,0);assert.equal((await handleSubmission(req(fixture()),{},writer)).status,200);assert.equal(calls,1);});
test('HTTP errors never claim a saved submission or disclose integration internals',async()=>{const r=await handleSubmission(req(fixture()),{},async()=>{throw new Error('secret-url-token');});assert.equal(r.status,502);assert.ok(!(await r.text()).includes('secret-url-token'));assert.equal((await handleSubmission(req(fixture()),{})).status,503);});

function receiver(){
 const rows:unknown[][]=[];let lockHeld=false;const counters=new Map<string,string>();
 const sheet={getMaxColumns:()=>55,getLastRow:()=>rows.length,setFrozenRows:()=>{},setColumnWidths:()=>{},setColumnWidth:()=>{},setRowHeight:()=>{},appendRow:(r:unknown[])=>rows.push(r),getRange:(row:number,col:number,count=1,width=1)=>{const range={setValues:(v:unknown[][])=>{rows[row-1]=v[0];return range;},setBackground:()=>range,setFontColor:()=>range,setFontWeight:()=>range,setWrap:()=>range,getValues:()=>rows.slice(row-1,row-1+count).map(r=>r.slice(col-1,col-1+width)),getValue:()=>rows[row-1]?.[col-1],createTextFinder:(id:string)=>({matchEntireCell:()=>({findNext:()=>{const at=rows.findIndex((r,i)=>i>=row-1&&r[0]===id);return at<0?null:{getRow:()=>at+1};}})})};return range;}};
 const context=vm.createContext({PropertiesService:{getScriptProperties:()=>({getProperty:(key:string)=>key==='WEBHOOK_SECRET'?secret:'test-sheet'})},Utilities:{Charset:{UTF_8:'utf8'},computeHmacSha256Signature:(payload:string,key:string)=>[...createHmac('sha256',key).update(payload).digest()]},ContentService:{MimeType:{JSON:'json'},createTextOutput:(s:string)=>({setMimeType:()=>s})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>rows.length?sheet:null,insertSheet:()=>sheet}),flush:()=>{}},LockService:{getScriptLock:()=>({tryLock:()=>{lockHeld=true;return true;},hasLock:()=>lockHeld,releaseLock:()=>{lockHeld=false;}})},CacheService:{getScriptCache:()=>({get:(k:string)=>counters.get(k),put:(k:string,v:string)=>counters.set(k,v)})}});
 vm.runInContext(readFileSync(new URL('../integrations/google-sheets/Code.gs',import.meta.url),'utf8'),context);
 return {rows,call:(data:unknown)=>{context.event={postData:{contents:JSON.stringify(data)}};return JSON.parse(vm.runInContext('doPost(event)',context));},locked:()=>lockHeld};
}
test('receiver integration: authenticated row, duplicate retry, conflicting content, formula escaping',()=>{const r=receiver();const data=validateSubmission({...fixture(),candidate:{...fixture().candidate,name:'=IMPORTXML("x")'}});assert.equal(r.call(signedEnvelope(data,secret)).ok,true);assert.equal(r.rows.length,2);assert.equal(r.rows[1][4],'\'=IMPORTXML("x")');assert.equal(r.call(signedEnvelope(data,secret)).duplicate,true);assert.equal(r.rows.length,2);assert.equal(r.call(signedEnvelope({...data,candidate:{...data.candidate,name:'Изменено'}},secret)).code,'ID_CONFLICT');assert.equal(r.rows.length,2);assert.equal(r.locked(),false);});
test('receiver rejects unsigned and expired writes; no rows created',()=>{const r=receiver();const data=validateSubmission(fixture());const envelope=signedEnvelope(data,secret);assert.equal(r.call({...envelope,signature:'0'.repeat(64)}).code,'UNAUTHORIZED');assert.equal(r.call(signedEnvelope(data,secret,new Date(0))).code,'EXPIRED');assert.equal(r.rows.length,0);});
