import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Code2, PenTool, Search, Users, Check, Clock3 } from 'lucide-react';

const tracks = [
 {icon:Code2,n:'01',title:'Создавать продукты',text:'Сайты, приложения и инструменты, которые решают реальные задачи университетской жизни.'},
 {icon:PenTool,n:'02',title:'Проектировать опыт',text:'Исследовать путь пользователя, придумывать понятные интерфейсы и визуальные решения.'},
 {icon:Search,n:'03',title:'Проверять идеи',text:'Разговаривать со студентами, изучать потребности и превращать наблюдения в гипотезы.'},
 {icon:Users,n:'04',title:'Объединять людей',text:'Работать с контентом, организовывать совместную работу и помогать команде двигаться вперёд.'},
];
export default function Home(){return <div className="site-shell landing">
 <header className="site-header"><Link className="brand" href="/"><span className="brand-icon">dh<span>↗</span></span><span>digital hub<span className="brand-caption">УНИВЕРСИТЕТСКОЕ СООБЩЕСТВО</span></span></Link><nav aria-label="Главная навигация"><a href="#about">О проекте</a><a href="#tracks">Направления</a><a href="#how">Как присоединиться</a></nav><Link className="header-apply" href="/questionnaire">Стать резидентом <ArrowUpRight size={16}/></Link></header>
 <main>
  <section className="landing-hero"><div><span className="admission-badge"><span/> Знакомимся с первыми резидентами</span><h1>Из «а что, если»<br/>в <em>«мы сделали».</em></h1><p>Digital Hub — место внутри университета, где студенты объединяются в команды, учатся друг у друга и создают цифровые проекты.</p><div className="hero-actions"><Link className="primary-button" href="/questionnaire">Найти своё место в команде <ArrowRight size={18}/></Link><span><Clock3 size={16}/> Знакомство займёт 7–10 минут</span></div></div><aside className="hero-note"><div className="eyebrow">ТВОЙ ПЕРВЫЙ ШАГ</div><h2>Не идеальное резюме.<br/>Интерес и готовность пробовать.</h2><p>Расскажи о себе и получи командный профиль. Он поможет обсудить подходящую роль и комфортный ритм участия.</p><div className="hero-note-items"><span><Check size={17}/> Опыт не обязателен</span><span><Check size={17}/> Разные специальности</span><span><Check size={17}/> Честно о доступном времени</span></div><div className="hero-note-footer"><strong>30</strong><span>вопросов о тебе<br/>и работе с людьми</span><ArrowUpRight size={30}/></div></aside></section>
  <section id="about" className="about-section"><div className="eyebrow">О DIGITAL HUB</div><div><h2>Учиться на том,<br/>что имеет смысл.</h2><p>Здесь важны не только технологии. Хорошему проекту нужны люди, которые умеют замечать проблемы, слушать, договариваться и доводить начатое до результата.</p><p>Найди свою первую задачу — от исследования и дизайна до разработки, коммуникаций и организации команды.</p></div></section>
  <section id="tracks" className="tracks-section"><div className="section-title"><div><div className="eyebrow">НАПРАВЛЕНИЯ</div><h2>Разные сильные стороны.<br/>Общий результат.</h2></div><p>Выбирай по интересу.<br/>Первую роль можно попробовать и пересмотреть.</p></div><div className="track-grid">{tracks.map(t=><article key={t.n}><div><t.icon size={24}/><span>{t.n}</span></div><h3>{t.title}</h3><p>{t.text}</p></article>)}</div></section>
  <section id="how" className="how-section"><div><div className="eyebrow">КАК ПРИСОЕДИНИТЬСЯ</div><h2>Начнём со знакомства.</h2><p>Опрос помогает понять, как тебе комфортнее работать. Он не выносит автоматическое решение о приёме.</p><Link className="primary-button" href="/questionnaire">Пройти знакомство <ArrowRight size={18}/></Link></div><ol><li><span>01</span><div><h3>Расскажи о себе</h3><p>Имя, учебная группа и контакт для связи — чтобы куратор мог сопоставить профиль с тобой.</p></div></li><li><span>02</span><div><h3>Ответь на 30 вопросов</h3><p>Мотивация, работа в команде, ответственность и реальное время на проект.</p></div></li><li><span>03</span><div><h3>Получи свой профиль</h3><p>Восемь шкал, подходящие роли и рекомендации. После твоего согласия результат будет записан в таблицу проекта.</p></div></li></ol></section>
  <section className="faq-section"><div className="eyebrow">ПЕРЕД СТАРТОМ</div><h2>Частые вопросы</h2><details><summary>Можно без опыта в IT?</summary><p>Да. В проекте нужны исследование, дизайн, контент и организация работы. В опросе можно указать, что ты ещё выбираешь направление.</p></details><details><summary>Сколько времени нужно выделять?</summary><p>Укажи реальную нагрузку с учётом учёбы и отдыха. Можно начать с 1–3 часов в неделю или сначала познакомиться без регулярных обязательств.</p></details><details><summary>Кто увидит мои ответы?</summary><p>После согласия ответы и профиль записываются в Google Таблицу проекта для работы куратора. Другим участникам сайта они не показываются. Подробнее — <Link href="/privacy">об использовании данных</Link>.</p></details><details><summary>Это психологическая диагностика?</summary><p>Нет. Это авторская самооценка для разговора о командной работе. Она не ставит диагнозов и не заменяет знакомство и пробную задачу.</p></details></section>
 </main><footer><span>digital hub ✳ Создаём вместе.</span><Link href="/privacy">Об использовании данных</Link><Link href="/questionnaire">Стать резидентом ↗</Link></footer>
</div>}
